# Windows packaging script for HongJing (Win10 1809+)
# Usage: powershell -ExecutionPolicy Bypass -File scripts/package_win.ps1
#
# Requirements:
#   - Inno Setup 6 (ISCC.exe in PATH or default install location)
#   - flutter + dart in PATH
#
# Optional:
#   - Authenticode signing: $env:WIN_PFX_BASE64 / $env:WIN_PFX_PASSWORD

$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")

# Read version from pubspec.yaml
$pubspec = Get-Content "pubspec.yaml" | Where-Object { $_ -match "^version:" }
$AppVersion = ($pubspec -replace "^version:\s*", "") -replace "\+.*$", ""
$AppVersion = $AppVersion.Trim()
if (-not $AppVersion) { $AppVersion = "1.0.3" }
Write-Host "==> Version: $AppVersion"

# [1/3] Flutter build
Write-Host "==> [1/3] flutter build windows --release"
flutter pub get
flutter build windows --release

$BUILD = "build\windows\x64\runner\Release"
if (-Not (Test-Path $BUILD)) {
  Write-Error "Build output not found: $BUILD"
  exit 1
}
$MainExe = Join-Path $BUILD "scrcpy_client_flutter.exe"
if (-Not (Test-Path $MainExe)) {
  Write-Error "Main executable not found: $MainExe"
  exit 1
}

# 内嵌 hdc.exe 及其依赖库到 tools/ 子目录
$hdcSrc = Join-Path $PSScriptRoot "..\bundled_tools\hdc.exe"
if ($hdcSrc) { $hdcSrc = [System.IO.Path]::GetFullPath($hdcSrc) }
$toolsDir = Join-Path $BUILD "tools"
if ($hdcSrc -and (Test-Path $hdcSrc)) {
  New-Item -ItemType Directory -Force -Path $toolsDir | Out-Null
  Copy-Item $hdcSrc $toolsDir
  Write-Host "  [bundled] hdc.exe -> $toolsDir"
  # hdc.exe 依赖 libusb_shared.dll
  $dllSrc = Join-Path $PSScriptRoot "..\bundled_tools\libusb_shared.dll"
  if ($dllSrc) { $dllSrc = [System.IO.Path]::GetFullPath($dllSrc) }
  if ($dllSrc -and (Test-Path $dllSrc)) {
    Copy-Item $dllSrc $toolsDir
    Write-Host "  [bundled] libusb_shared.dll -> $toolsDir"
  }
} else {
  Write-Host "  [warn] bundled_tools\hdc.exe not found, skipping bundled hdc"
}

# [2/3] Inno Setup packaging
Write-Host "==> [2/3] Generating Inno Setup script and packaging"
New-Item -ItemType Directory -Force -Path "build\dist" | Out-Null
$ISS = "scripts\installer.iss"
$IconDst = "windows\runner\resources\app_icon.ico"

$SetupIconLine = ""
if (Test-Path $IconDst) {
  $SetupIconLine = "SetupIconFile=..\" + $IconDst
}

# 用 Unicode 码点构造中文，绕过 PS1 文件编码问题（PS5 默认 GBK 读取 UTF-8 无 BOM 文件）
# 鸿=U+9E3F 镜=U+955C 启=U+542F 动=U+52A8
$CN_AppName   = [char]0x9E3F + [char]0x955C          # 鸿镜
$CN_Launch    = [char]0x542F + [char]0x52A8 + " " + $CN_AppName  # 启动 鸿镜

$ChineseLanguageFile = "compiler:Languages\ChineseSimplified.isl"
if ($env:INNO_CHINESE_SIMPLIFIED_ISL) {
  if (-not (Test-Path $env:INNO_CHINESE_SIMPLIFIED_ISL)) {
    Write-Error "Inno Setup language file not found: $env:INNO_CHINESE_SIMPLIFIED_ISL"
    exit 1
  }
  $ChineseLanguageFile = [System.IO.Path]::GetFullPath($env:INNO_CHINESE_SIMPLIFIED_ISL)
}

# Build ISS content line by line
$lines = @()
$lines += "; HongJing installer (auto-generated by package_win.ps1)"
$lines += "#define MyAppName `"$CN_AppName`""
$lines += '#define MyAppExe  "scrcpy_client_flutter.exe"'
$lines += "#define MyAppVersion `"$AppVersion`""
$lines += '#define MyAppPublisher "Guangzhou Shirui Electronics Co., Ltd."'
$lines += ""
$lines += "[Setup]"
$lines += "AppId={{B6E4D4F9-9E86-4E7F-8A1C-C6F9B0F8C3A1}}"
$lines += "AppName={#MyAppName}"
$lines += "AppVersion={#MyAppVersion}"
$lines += "AppPublisher={#MyAppPublisher}"
$lines += "DefaultDirName={autopf}\HongJing"
$lines += "DefaultGroupName={#MyAppName}"
$lines += "OutputDir=..\build\dist"
$lines += "OutputBaseFilename=HongJing-Setup-$AppVersion"
$lines += "Compression=lzma"
$lines += "SolidCompression=yes"
$lines += "ArchitecturesInstallIn64BitMode=x64compatible"
$lines += "WizardStyle=modern"
$lines += "MinVersion=10.0.17763"
if ($SetupIconLine) { $lines += $SetupIconLine }
$lines += "UninstallDisplayIcon={app}\{#MyAppExe}"
$lines += "PrivilegesRequired=lowest"
$lines += "PrivilegesRequiredOverridesAllowed=dialog"
$lines += ""
$lines += "[Languages]"
$lines += "Name: `"chs`"; MessagesFile: `"$ChineseLanguageFile`""
$lines += ""
$lines += "[Files]"
$lines += "Source: `"..\$BUILD\*`"; DestDir: `"{app}`"; Flags: recursesubdirs ignoreversion"
$lines += ""
$lines += "[Icons]"
$lines += 'Name: "{userprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExe}"'
$lines += 'Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExe}"'
$lines += ""
$lines += "[Run]"
$lines += "Filename: `"{app}\{#MyAppExe}`"; Description: `"$CN_Launch`"; Flags: nowait postinstall skipifsilent"

$IssPath = Join-Path (Get-Location) $ISS
# 写成 GBK（系统 ANSI），Inno Setup 默认按 ANSI 读取，不需要 BOM
[System.IO.File]::WriteAllLines($IssPath, $lines, [System.Text.Encoding]::GetEncoding(936))

# Locate ISCC.exe
$ISCC = $null
$isccCmd = Get-Command ISCC.exe -ErrorAction SilentlyContinue
if ($isccCmd) {
  $ISCC = $isccCmd.Source
} else {
  $pf86 = [System.Environment]::GetEnvironmentVariable("ProgramFiles(x86)")
  $pf64 = [System.Environment]::GetEnvironmentVariable("ProgramFiles")
  $candidates = @(
    (Join-Path $pf86 "Inno Setup 6\ISCC.exe"),
    (Join-Path $pf64 "Inno Setup 6\ISCC.exe")
  )
  foreach ($c in $candidates) {
    if (Test-Path $c) { $ISCC = $c; break }
  }
}
if (-not $ISCC) {
  Write-Error "ISCC.exe not found. Install Inno Setup 6: https://jrsoftware.org/isdl.php"
  exit 1
}
Write-Host "  Using ISCC: $ISCC"

& $ISCC $ISS
if ($LASTEXITCODE -ne 0) {
  Write-Error "Inno Setup failed (exit $LASTEXITCODE)"
  exit 1
}

$SetupExe = Get-ChildItem "build\dist\HongJing-Setup-*.exe" | Select-Object -First 1
if (-not $SetupExe) {
  Write-Error "Installer not found in build\dist\"
  exit 1
}
Write-Host "  Installer: $($SetupExe.FullName)"

# [3/3] Authenticode signing (optional)
Write-Host "==> [3/3] Optional: Authenticode signing"
if ($env:WIN_PFX_BASE64 -and $env:WIN_PFX_PASSWORD) {
  $signtool = $null
  $stCmd = Get-Command signtool.exe -ErrorAction SilentlyContinue
  if ($stCmd) {
    $signtool = $stCmd.Source
  } else {
    $sdkRoots = @(
      "${env:ProgramFiles(x86)}\Windows Kits\10\bin",
      "${env:ProgramFiles}\Windows Kits\10\bin"
    )
    foreach ($root in $sdkRoots) {
      $found = Get-ChildItem -Path $root -Filter "signtool.exe" -Recurse -ErrorAction SilentlyContinue |
               Where-Object { $_.FullName -match "x64" } |
               Sort-Object FullName -Descending |
               Select-Object -First 1
      if ($found) { $signtool = $found.FullName; break }
    }
  }
  if (-not $signtool) {
    Write-Warning "signtool.exe not found, skipping signing"
  } else {
    $pfx = Join-Path $env:TEMP "win_sign.pfx"
    try {
      [IO.File]::WriteAllBytes($pfx, [Convert]::FromBase64String($env:WIN_PFX_BASE64))
      & $signtool sign /f $pfx /p $env:WIN_PFX_PASSWORD `
        /tr http://timestamp.digicert.com /td sha256 /fd sha256 $SetupExe.FullName
      if ($LASTEXITCODE -ne 0) { Write-Warning "Signing failed (exit $LASTEXITCODE)" }
      else { Write-Host "  Signing complete" }
    } finally {
      Remove-Item $pfx -ErrorAction SilentlyContinue
    }
  }
} else {
  Write-Host "  Skipped: WIN_PFX_BASE64 / WIN_PFX_PASSWORD not set"
}

Write-Host ""
Write-Host "Done. Installer: build\dist\$($SetupExe.Name)"
